name: HerobrineAI
main: org.jakub1221.herobrineai.HerobrineAI
version: 4.50
description: HerobrineAI is Minecraft server plugin for bukkit/spigot that brings Herobrine to life.
commands:
    hb-ai:
      description: Main command.
      usage: /hb-ai help
    hb:
      description: Main command.
      usage: /hb help